import Head from 'next/head'
import Header from '@components/header'
import Navigation from '@components/navigation'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <Header />
      </main>
    </>
  )
}

export default Home
