import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Header from '@components/header'
import Navigation from '@components/navigation'
import { getPostlist } from '@shared/util'
import Link from 'next/link'

type PostListT = string[]

const Home = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Navigation />
      <Header />
      {posts.length > 0 && (
        <ul>
          {posts.map(slug => (
            <Link key={slug} href={`/posts/${slug}`}>
              <a>{slug.replace(/-/g, ' ')}</a>
            </Link>
          ))}
        </ul>
      )}
    </main>
  </>
)

export const getStaticProps = async () => {
  const posts:PostListT = getPostlist()

  return {
    props: {
      posts
    }
  }
}

export default Home
